# This workflow will build all geoipsets, load each set into nftables/iptables and use the set in a rule

name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '14 14 * * 3'

jobs:
  generate-geoipsets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build geoipsets
        run: |
          python -m geoipsets --provider dbip --firewall nftables --firewall iptables --address-family ipv4 --address-family ipv6
        working-directory: ./python
#  run-integration-tests:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        provider: [ dbip, maxmind ]
#        firewall: [ nftset, ipset ]
#        address-family: [ ipv4, ipv6 ]